
google:
  client-id: 492958510752-gi5q044smefsmklsellklr9861bql0ie.apps.googleusercontent.com
  client-secret: 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

jwt:
  secretKey: "dfghjklfghjklkjhgfrt678654redfghjkmnbgt7ikjhbvgffcvhsjdhsajhgsjhdgshjhjkhui876tyjkmnb"
